### ISSUE TITLE
sword cant be built from git

### ISSUE THREAD

**Issue by mintuser4444** [ezra-bible-app/node-sword-interface#28]
```
npm ERR! CMake Error at /usr/share/cmake-3.10/Modules/FindSubversion.cmake:99 (message):
npm ERR!   Command "/usr/bin/svn info
npm ERR!   /home/user/n/lib/node_modules/node-sword-interface/sword" failed with
npm ERR!   output:
npm ERR!
npm ERR!   svn: E155007: '/home/user/n/lib/node_modules/node-sword-interface/sword' is
npm ERR!   not a working copy
npm ERR!

```
i could `svn checkout https://crosswire.org/svn/sword/trunk sword` and get it to build.  also the build requirements on ubuntu are build-essential pkg-config libcurl4-openssl-dev libicu-dev cmake subversion

**Comment by tobias-klein** [comment]
Thank you for reporting this. Could you share some more information:

Which extract distribution and version of that distribution are you using?

What was the sequence of commands/actions you performed to arrive at this result?

**Comment by mintuser4444** [comment]
node 16.17.1 npm 8.15.0 linux 4.4.0-19041-Microsoft on wsl 1.  the problem is that svn doesnt recognize the git repo so cmake doesnt work but since svn is a build requirement you could use svn here https://github.com/ezra-bible-app/node-sword-interface/blob/master/scripts/build_sword.sh#L33 but it looks like i can set LINK_SYSTEM_SWORD https://github.com/ezra-bible-app/node-sword-interface/blob/master/scripts/build_sword.sh#L25
so i tried to apt install libsword-dev and set LINK_SYSTEM_SWORD and got this error instead
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/sword_backend/repository_interface.cpp: In member function ‘void RepositoryInterface::resetMgr()’:
npm ERR! ../src/sword_backend/repository_interface.cpp:72:24: error: ‘class sword::InstallMgr’ has no member named ‘setTimeoutMillis’
npm ERR!      this->_installMgr->setTimeoutMillis(timeoutMillis);
npm ERR!                         ^~~~~~~~~~~~~~~~
npm ERR! make: *** [Release/obj.target/node_sword_interface/src/sword_backend/repository_interface.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by tobias-klein** [comment]
This works on (native) Linux. Never tried this in WSL before. What's your use case for building in WSL?

**Comment by tobias-klein** [comment]
The build error above means that the used SWORD version is older than the one we work with (SVN trunk) and therefore not compatible.

**Comment by tobias-klein** [comment]
@mintuser4444 Any feedback before I close this issue?

**Comment by mintuser4444** [comment]
after installing 3.24 from the kitware ppa i was able to get node-sword-interface to build on 18.04.  i also tried on 20.04 and got
```npm ERR! CMake Error at CMakeLists.txt:95 (ADD_LIBRARY):
npm ERR!   Cannot find source file:
npm ERR!
npm ERR!     src/utilfuns/zlib/adler32.c
npm ERR!
npm ERR!   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
npm ERR!   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
npm ERR!
npm ERR!
npm ERR! CMake Error at CMakeLists.txt:95 (ADD_LIBRARY):
npm ERR!   No SOURCES given to target: sword_static
npm ERR!
npm ERR!
npm ERR! CMake Generate step failed.  Build files cannot be regenerated correctly.```

**Comment by tobias-klein** [comment]
Ok. The last thing is a bug in the CMake configuration of sword. You need to have zlib1g-dev installed for it to work on your 20.04 environment. I also noticed this recently and updated the Readme, adding the zlib1g-dev dependency.

I am closing this issue now!
